services:
  # postgres:
  #   image: postgres:15
  #   container_name: postgres
  #   environment:
  #     POSTGRES_DB: ${POSTGRES_DB}
  #     POSTGRES_USER: ${POSTGRES_USER}
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   networks:
  #     - app-network
  #   restart: unless-stopped

  backend:
    build:
      context: ../backend
      dockerfile: ../dev-config/Dockerfile.backend
    container_name: genshin_tournamemt
    ports:
      - "5000:5000"
    volumes:
      - ../backend:/app
    environment:
      PORT: ${PORT}
      SERVER_URL: ${SERVER_URL}
      JWT_SECRET: ${JWT_SECERET}
      FRONTEND_URL: ${FRONTEND_URL}
    networks:
      - app-network


networks:
  app-network:
    driver: bridge